package phase02;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.converter.BeanOutputConverter;
import phase02.DecisionModelContracts.DecisionEnvelope;
import phase02.DecisionModelContracts.OptimizationDecision;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Service under test — THE ONLY FILE YOU MODIFY.
 * <p>
 * Seeded with defects across 8 scenarios in Decision Schemas & Resilient Extraction:
 * - Scenario 1: Format instruction generation via BeanOutputConverter.getFormat().
 * - Scenario 2: Direct BeanOutputConverter deserialization into OptimizationDecision.
 * - Scenario 3: Markdown fence & conversational preamble sanitization.
 * - Scenario 4: TigerStyle domain invariants and discriminated union cross-field rules.
 * - Scenario 5: Generic collection extraction (List<OptimizationDecision>) via ParameterizedTypeReference.
 * - Scenario 6: Fallback semi-structured diagnostic prose extraction (FallbackDecisionExtractor).
 * - Scenario 7: Saga DECIDE closed-loop one-shot feedback schema repair.
 * - Scenario 8: Strict retry limit enforcement (capped at 1 retry, throws IllegalStateException).
 */
public class DecisionEngineUnderTest {

    private final BeanOutputConverter<OptimizationDecision> decisionConverter;

    public DecisionEngineUnderTest() {
        this.decisionConverter = new BeanOutputConverter<>(OptimizationDecision.class);
    }

    /**
     * Scenario 1: Generate schema format instructions for prompt injection.
     * Must return non-blank JSON schema directives generated by decisionConverter.getFormat().
     */
    public String generateFormatInstructions() {
        // DEFECT (Scenario 1): Returns blank string instead of delegating to decisionConverter.getFormat().
        return "";
    }

    /**
     * Scenario 2: Direct record deserialization from clean JSON.
     * Invariants: rawJson must not be null or blank.
     * Must deserialize raw JSON cleanly into OptimizationDecision.
     */
    public OptimizationDecision parseDecision(String rawJson) {
        // DEFECT (Scenario 2): Missing fail-fast boundary validation and returns null.
        return null;
    }

    /**
     * Scenario 3: Defensive markdown fence stripping & conversational preamble sanitization.
     * Real LLMs wrap JSON inside conversational text and markdown fences:
     * ```json
     * { ... }
     * ```
     * Must extract the JSON substring from first '{' to last '}' before delegating to decisionConverter.
     */
    public OptimizationDecision extractFromConversationalText(String markdownPayload) {
        // DEFECT (Scenario 3): Passes raw conversational text directly to converter without stripping fences.
        return decisionConverter.convert(markdownPayload);
    }

    /**
     * Scenario 4: TigerStyle domain invariants and cross-field rules.
     * Enforces boundaries on OptimizationDecision:
     * - hypothesis: category matches ^H[1-7]$, confidence in [0.0, 1.0], rationale non-blank.
     * - prediction: metric is {p95, median, rps, error_rate}, direction is {improve, regress, neutral}, signalToEliminate non-blank.
     * - ledger: hypothesisCategory matches ^H[1-7]$, direction is {strengthen, weaken}, reason non-blank.
     * - change (cross-field):
     *     - if kind is "edits": edits must not be null or empty; template must be null or blank.
     *     - if kind is "template": template must be one of {jar-unpack, hikari-pool, virtual-threads}; edits must be null or empty.
     *     - any other kind throws IllegalArgumentException.
     * Throws IllegalArgumentException on any violation.
     */
    public void validateCrossFieldRules(OptimizationDecision decision) {
        // DEFECT (Scenario 4): No-op; fails to validate domain invariants or cross-field constraints.
    }

    /**
     * Scenario 5: Generic collections extraction via ParameterizedTypeReference.
     * Invariants: jsonArrayPayload must not be null or blank.
     * Must use new BeanOutputConverter<>(new ParameterizedTypeReference<List<OptimizationDecision>>() {})
     * to deserialize JSON array into a strongly-typed List<OptimizationDecision>.
     */
    public List<OptimizationDecision> parseDecisionBatch(String jsonArrayPayload) {
        // DEFECT (Scenario 5): Returns empty list instead of parsing parameterized generic collection.
        return List.of();
    }

    /**
     * Scenario 6: Fallback semi-structured diagnostic prose extraction (FallbackDecisionExtractor pattern).
     * When model articulates reasoning in prose without JSON brackets:
     * - Uses regex to extract (pre-compiled patterns provided below):
     *     - hypothesis category (H1-H7): {@code PROSE_HYPOTHESIS_PATTERN} ("(?i)\\b(H[1-7])\\b")
     *     - confidence (default 0.8): {@code PROSE_CONFIDENCE_PATTERN} ("(?i)confidence\\s+([0-9]*\\.?[0-9]+)")
     *     - template (jar-unpack, hikari-pool, virtual-threads): {@code PROSE_TEMPLATE_PATTERN} ("(?i)template\\s+([a-z0-9-]+)")
     *     - signal to eliminate (default JavaMonitorEnter): {@code PROSE_SIGNAL_PATTERN} ("(?i)(JavaMonitorEnter|SocketRead|ObjectAllocationSample)")
     *     - target metric (default p95): {@code PROSE_METRIC_PATTERN} ("(?i)\\b(p95|median|rps|error_rate)\\b")
     *     - ledger direction (strengthen/weaken, default strengthen): {@code PROSE_DIRECTION_PATTERN} ("(?i)\\b(strengthen|weaken)\\b")
     * - Reconstructs and returns an OptimizationDecision with:
     *     - hypothesis: category, confidence, and rationale
     *     - prediction: metric, direction fixed to "improve", and signalToEliminate
     *     - ledger: hypothesisCategory, ledger direction (default "strengthen"), and reason
     *     - change: kind = "template", template name, null edits, empty/null parameters
     * - Returns null if text is null, blank, or missing required diagnostic indicators (e.g. hypothesis or template).
     */
    public static final Pattern PROSE_HYPOTHESIS_PATTERN = Pattern.compile("(?i)\\b(H[1-7])\\b");
    public static final Pattern PROSE_CONFIDENCE_PATTERN = Pattern.compile("(?i)confidence\\s+([0-9]*\\.?[0-9]+)");
    public static final Pattern PROSE_TEMPLATE_PATTERN = Pattern.compile("(?i)template\\s+([a-z0-9-]+)");
    public static final Pattern PROSE_SIGNAL_PATTERN = Pattern.compile("(?i)(JavaMonitorEnter|SocketRead|ObjectAllocationSample)");
    public static final Pattern PROSE_METRIC_PATTERN = Pattern.compile("(?i)\\b(p95|median|rps|error_rate)\\b");
    public static final Pattern PROSE_DIRECTION_PATTERN = Pattern.compile("(?i)\\b(strengthen|weaken)\\b");

    public OptimizationDecision fallbackExtractFromProse(String proseText) {
        // DEFECT (Scenario 6): Returns null; does not attempt regex extraction from prose.
        return null;
    }

    /**
     * Scenario 7: One-shot feedback schema repair loop (Saga DECIDE pattern).
     * Invariants: client and promptText must not be null or blank.
     * Protocol:
     * 1. Attempt 1: Call client with promptText. Sanitize, parse, and validate with validateCrossFieldRules.
     * 2. If attempt 1 fails due to parsing or schema exception:
     *    Call client a second time with feedback prompt:
     *    "Previous proposal failed validation: " + e.getMessage() + ". Please fix the error and return strictly valid JSON matching the schema."
     *    Sanitize, parse, and validate second response.
     * 3. Return DecisionEnvelope.accepted(decision, attemptsUsed).
     */
    public DecisionEnvelope<OptimizationDecision> repairDecisionWithFeedback(ChatClient client, String promptText) {
        // DEFECT (Scenario 7): Returns null without attempting feedback repair.
        return null;
    }

    /**
     * Scenario 8: Enforce strict retry limit (prevent runaway infinite repair loops).
     * When both attempt 1 and attempt 2 fail:
     * MUST NOT retry a 3rd time!
     * Must throw IllegalStateException("Decision schema repair exceeded maximum attempts (1)").
     */
    public DecisionEnvelope<OptimizationDecision> enforceStrictRepairCircuitBreaker(ChatClient client, String promptText) {
        // DEFECT (Scenario 8): Returns null without enforcing retry limit.
        return null;
    }
}
